sudo: required
services:
  - docker

before_script:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

script:
  - docker build -t whereismytaco/ansible:2.2.1 --no-cache --pull .
  - docker push whereismytaco/ansible:2.2.1
  - docker tag whereismytaco/ansible:2.2.1 whereismytaco/ansible:latest
  - docker push whereismytaco/ansible:latest
